### PR TITLE
Fix bug in CommentBox

### PR DESCRIPTION
**Pull request by lifeiscontent**
When submitting a comment there was an issue because the CommentList was expecting an Array datatype.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@justin808 any updates on this?

**Comment by justin808** [comment]
I'll look at this today.

**Comment by justin808** [comment]
Hi @lifeiscontent, there's a bunch of issues here. First, we don't want to set the state of data to be the single value. Here's the right code:

```
  handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    comments.push(comment);
    this.setState({data: comments}, function() {
      // `setState` accepts a callback. To avoid (improbable) race condition,
      // `we'll send the ajax request right after we optimistically set the new
      // `state.
      $.ajax({
        url: this.props.url,
        dataType: 'json',
        type: 'POST',
        data: { comment: comment },
        success: function(data) {
          var newData = this.state.data.slice(0); // clone the array, don't modify state array directly
          newData.push(data);
          this.setState({data: newData});
        }.bind(this),
        error: function(xhr, status, err) {
          console.error(this.props.url, status, err.toString());
        }.bind(this)
      });
    });
  },
```

If you like, you can update your PR and I'll accept it. Thanks for helping out. It would be great to update this project to the latest versions of React, etc. If you can submit a PR for that or include in this, I'll get everything updated.

**Comment by lifeiscontent** [comment]
@justin808 what benefit does the cloning give?

**Comment by justin808** [comment]
@lifeiscontent Per the rules of using react, don't modify the array in the state directly.

**Comment by jbhatab** [comment]
I commented on this in  the other pull request, https://github.com/justin808/react-rails-tutorial/pull/3.

From the looks of this, you are doing optimistic updating when submitting comments so you have already added the comment to the state before you send the ajax call to the sever. In the success callback, it should just do nothing, so we should just remove that line entirely. We do need to add a way for it to remove the comment though if it fails. So it should probably look something like this,

```
 handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    comments.push(comment);
    this.setState({data: comments}, function() {
      // `setState` accepts a callback. To avoid (improbable) race condition,
      // `we'll send the ajax request right after we optimistically set the new
      // `state.
      $.ajax({
        url: this.props.url,
        dataType: 'json',
        type: 'POST',
        data: { comment: comment },
        success: function(data) {
        }.bind(this),
        error: function(xhr, status, err) {
          comments.pop()
          this.setState(data: comments);
          console.error(this.props.url, status, err.toString());
        }.bind(this)
      });
    });
  },
```

I could be reading this wrong, but that at least makes sense to me. I do think that all of the comment stuff is gonna get a pretty big rewrite though when the updates come in with es6.

**Comment by jbhatab** [comment]
Fixed here: https://github.com/justin808/react-rails-tutorial/pull/5

**Pull request closed without merging**
