### PR TITLE
Update handleCommentSubmit to call loadCommentsFromServer on successful ajax comment submission

### PR DESCRIPTION
**Pull request by andrewdavidkay**
Hey Justin, Great tutorial! It has really helped me get started using React and Rails. 

One thing: I think the original Facebook tutorial expects all the comments to be returned here so when you return just one Comment, the script is breaking with a _Uncaught TypeError: this.props.data.map is not a function_ because it is expecting an array of multiple objects. I only caught this because I removed the polling from my app and noticed that it wasn't working without polling. Also if it did work, then the page would be re-rendered with only the new comment. My solution was just to call loadCommentsFromServer again. Thanks, Andy.

### CODE REVIEW

**Comment by justin808** [comment]
Rather than have callback issue another callback, should we fix the server side?

However, I'm working mostly in https://github.com/justin808/react-webpack-rails-tutorial right now, so I won't have a chance to look at this immediately.

**Comment by jbhatab** [comment]
From the looks of this, you are doing optimistic updating when submitting comments so you have already added the comment to the state before you send the ajax call to the sever. In the success callback, it should just do nothing, so we should just remove that line entirely. We do need to add a way for it to remove the comment though if it fails. So it should probably look something like this,

```
 handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    comments.push(comment);
    this.setState({data: comments}, function() {
      // `setState` accepts a callback. To avoid (improbable) race condition,
      // `we'll send the ajax request right after we optimistically set the new
      // `state.
      $.ajax({
        url: this.props.url,
        dataType: 'json',
        type: 'POST',
        data: { comment: comment },
        success: function(data) {
        }.bind(this),
        error: function(xhr, status, err) {
          comments.pop()
          this.setState(data: comments);
          console.error(this.props.url, status, err.toString());
        }.bind(this)
      });
    });
  },
```

I could be reading this wrong, but that at least makes sense to me. I do think that all of the comment stuff is gonna get a pretty big rewrite though when the updates come in with es6.

**Comment by justin808** [comment]
@jbhatab if you've confirmed your fix or the PR works, please merge to master. Thanks.

**Comment by jbhatab** [comment]
Fixed in https://github.com/justin808/react-rails-tutorial/pull/5

**Pull request closed without merging**
